// actions related to the app
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_NODE_ENV = 'CHANGE_NODE_ENV'
export const CHANGE_CHOSEN_INTENTS = 'CHANGE_CHOSEN_INTENTS'
export const CHANGE_SELECTED_DATES = 'CHANGE_SELECTED_DATES'
export const SET_ALL_INTENTS = 'SET_ALL_INTENTS'
export const SET_UNIQUE_INTENTS = 'SET_UNIQUE_INTENTS'
export const CHANGE_SELECTED_INTENTS = 'CHANGE_SELECTED_INTENTS'
export const CHANGE_SESSION_CONVO = 'CHANGE_SESSION_CONVO'
