// actions related to the app
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_NODE_ENV = 'CHANGE_NODE_ENV'
export const CHANGE_CHOSEN_INTENTS = 'CHANGE_CHOSEN_INTENTS'
export const CHANGE_SELECTED_DATES = 'CHANGE_SELECTED_DATES'
export const CHANGE_ALL_INTENTS = 'CHANGE_ALL_INTENTS'
